### ISSUE TITLE
PUT run data to DB

### ISSUE THREAD

**Issue by shanemcgraw** [boisterousSplash/Bolt#114]

**Comment by shanemcgraw** [comment]
Bolt -> Run -> OnFinish() post to DB

**Comment by shanemcgraw** [comment]
@epaepke here's the schema of the achievements part of the DB. Does this look okay?

<img width="892" alt="screen shot 2016-02-22 at 12 07 35 pm" src="https://cloud.githubusercontent.com/assets/10692718/13231120/1e1bb016-d95d-11e5-9012-bde6308ba09c.png">

**Comment by epaepke** [comment]
@shanemcgraw Looks good, thanks for the update! So are we planning to include the achievements object in the already existing user schema? Alternatively, we can create another collection and link them using the runner id. I prefer the former.

**Comment by shanemcgraw** [comment]
@epaepke Yeah, I agree- setting it to the existing user schema seems like the easiest option at this point. We can always factor it out to another collection if we find that we need more data than just an object of medals (which we very well may in the future), but I think we'll be good for now.

But anyway, right on! I'll create the schema and PR it in once I finish up the POST req.
